In [2]:
import tensorflow as tf

In [17]:
n= tf.random.normal((1,4,1)) #batch size =1 and vector of 4X1 of normal distribution
n

<tf.Tensor: shape=(1, 4, 1), dtype=float32, numpy=
array([[[-0.19545522],
        [-0.14027552],
        [ 0.09213017],
        [ 0.4476665 ]]], dtype=float32)>

In [47]:
#create 1D convolution
# We dont need to specify the no. of input channels since we dont have control over it and is fixed.
#All we have control over is the Output channel, the height and width
# here output channel is 1 and of vector 3X1
#padding= VALID that means No padding, bias is 0
conv1= tf.keras.layers.Conv1D(1,3,1, "VALID", activation = None , bias_initializer= tf.keras.initializers.Constant(0))
conv1  

In [16]:
conv1(n)

<tf.Tensor: shape=(1, 2, 1), dtype=float32, numpy=
array([[[ 0.78645515],
        [-0.6544697 ]]], dtype=float32)>

# 2D convolution array of 16X16

In [25]:
#batch size=1, array= !6X16, no.of channels=1
k= tf.random.normal((1,16,16,1))
k.shape

TensorShape([1, 16, 16, 1])

In [117]:
# output channels=8,kernel size=5X5 and stride=1
conv2= tf.keras.layers.Conv2D(8,[5,5],1, "VALID", activation = None )
conv2

In [118]:
m=conv2(k)
m

<tf.Tensor: shape=(1, 12, 12, 8), dtype=float32, numpy=
array([[[[-0.7359458 ,  0.682473  ,  0.5238389 , ..., -0.15073946,
          -0.6179685 , -0.10726426],
         [ 0.3113655 , -0.03446725,  0.43872544, ...,  0.0293614 ,
          -0.18156742, -0.39470005],
         [-0.00369764,  0.28586295, -0.43836302, ...,  0.61517984,
           0.27508357,  0.52933884],
         ...,
         [-0.337543  , -0.16323747,  0.48332268, ...,  0.08462258,
          -0.079835  ,  0.08617   ],
         [-0.19489881,  0.5855575 , -0.19334194, ..., -0.16396515,
          -0.35188255,  0.12680697],
         [ 0.74555737, -0.0536602 ,  0.44061542, ...,  0.5481328 ,
          -0.40377113,  0.17531373]],

        [[-0.54463667, -0.13020366,  0.14149554, ...,  0.39976197,
           0.3480736 , -0.27686903],
         [-0.11177614,  0.81490225,  0.92958707, ...,  0.27879465,
          -0.27605283, -0.40693936],
         [ 0.3808675 ,  0.03255089,  0.83450323, ...,  0.1723101 ,
          -0.80531496, -0.058

In [119]:
m.shape

TensorShape([1, 12, 12, 8])

In [120]:
conv2.weights[0].shape
# kernel size, input channel, output channel  

TensorShape([5, 5, 1, 8])

In [121]:
# the value of bias 
conv2.weights[1].shape

TensorShape([8])

# lets take a example with bias

In [49]:
I= tf.constant([[[[1,-2],[2,1],[-2,3],[-1,2]],
                 [[2,2],[3,-2],[3,1],[-4,2]],
                 [[3,0],[-2,-2],[2,-1],[5,-2]],
                 [[0,0],[1,-1],[3,1],[0,1]]]])

In [50]:
I.shape 
#channels=2

TensorShape([1, 4, 4, 2])

In [122]:
# setting kernel with output channels=2,kernel size=2X2 and stride=1
#set bias =[1,2] and set kernel, data type is int
conv= tf.keras.layers.Conv2D(2,[2,2],1, "VALID", activation = None, 
    bias_initializer= tf.keras.initializers.Constant([1,2]),
    kernel_initializer=tf.keras.initializers.Constant([[[[1,-2],[-2,1]],
                                                         [[1,0],[0,1]]],
                                                         [[[3,1],[2,2]],
                                                         [[0,0], [0,4]]]]), dtype='int32')



In [112]:
T= conv(I)
T


<tf.Tensor: shape=(1, 3, 3, 2), dtype=int32, numpy=
array([[[[ 18,  -3],
         [  4,   5],
         [  3,  24]],

        [[ 11,  -7],
         [  1, -15],
         [  2,  -9]],

        [[  2, -10],
         [  6,   6],
         [ 21,   4]]]])>