In [1]:
import tensorflow as tf

In [3]:
k= tf.random.normal((1,4,4,1))
k

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float32, numpy=
array([[[[ 0.89904743],
         [ 1.5721245 ],
         [-0.73541266],
         [ 0.10020132]],

        [[ 1.2996981 ],
         [ 0.5372409 ],
         [-0.5250987 ],
         [-0.5599225 ]],

        [[-0.07059516],
         [ 0.74870986],
         [ 0.02494619],
         [ 0.1348635 ]],

        [[ 0.65263593],
         [ 0.26942626],
         [ 1.8604301 ],
         [-0.47736198]]]], dtype=float32)>

In [22]:
pool=tf.keras.layers.MaxPooling2D([2,2],[2,2], "valid")
pool

In [10]:
nextgrad= tf.ones((1,2,2,1))
nextgrad

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[1.],
         [1.]],

        [[1.],
         [1.]]]], dtype=float32)>

In [12]:
with tf.GradientTape(persistent= True) as t:
    t.watch(k)
    m=pool(k)
    m1= tf.multiply(nextgrad,m)
    

In [16]:
m

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[1.5721245 ],
         [0.10020132]],

        [[0.74870986],
         [1.8604301 ]]]], dtype=float32)>

In [18]:
m1

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[1.5721245 ],
         [0.10020132]],

        [[0.74870986],
         [1.8604301 ]]]], dtype=float32)>

In [21]:
gradinput= t.gradient(m1,k)
gradinput

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [1.],
         [0.],
         [1.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [1.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [1.],
         [0.]]]], dtype=float32)>